spring:
   datasource:
      url: jdbc:sqlserver://walkingtree1.database.windows.net:1433;database=students;user=ankit123@walkingtree1;password=ankit@123;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
      username: ankit123
      password: ankit@123
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
         dialect : org.hibernate.dialect.SQLServer2012Dialect
         
server:
   port: 9191